#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use App\Commands\MartianCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new MartianCommand());
$application->run();
