version: "3.9"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
